### ISSUE TITLE
Tutorial  example: Virus network cannot animate

### ISSUE THREAD

**Issue by alon-benari** [JoelForamitti/agentpy#1]
Trying to replicate the animation for virus network:

> ttributeError                            Traceback (most recent call last)
<ipython-input-20-0959dfd9dab4> in <module>
     15 fig, axs = plt.subplots(1, 2, figsize=(8, 4)) # Prepare figure
     16 parameters['population'] = 50 # Lower population for better visibility
---> 17 animation = ap.animate(VirusModel(parameters), fig, axs, animation_plot)

~/monocondaNew/lib/python3.7/site-packages/agentpy/analysis.py in animate(model, fig, axs, plot, steps, skip, fargs, **kwargs)
    136         plot(m, axs, *fargs)  # Perform plot
    137 
--> 138     ani = matplotlib.animation.FuncAnimation(
    139         fig, update, frames=frames, fargs=(model, axs, *fargs), **kwargs)  # noqa
    140 

AttributeError: module 'matplotlib' has no attribute 'animation'

what am I missing here?
Thanks

**Comment by JoelForamitti** [comment]
Please try to update your matplotlib library to the latest version (3.3.3) and let me know if the error persists.
In the next update I will try to declare version-specific dependencies so that this shouldn't happen anymore.

**Comment by alon-benari** [comment]
Yup, thank  you. That did the trick.
Thank you for authoring agentpy. The python native integrated visualization is great. I dont need to write JS like in mesa.
Well done.
