### ISSUE TITLE
KDTree not refreshed after remove_agents() called

### ISSUE THREAD

**Issue by zba18** [JoelForamitti/agentpy#12]
I think I may have found a bug in `space.py`

In my model, I have many agents, potentially removing each other on the same timestep.
I'm also trying to directly use the KDTree's `query()` function to find the nearest neighbor, since this is not yet a feature. (hope I can be able to implement this functionality soon)

What I've realised is that although I have removed agents in a given step, the KDTree still contains the agents' locations. This manifests as an `IndexError` when I try to run my nearest neighbor lookup - the agent is in the tree, but already removed from `env._sorted_agents`. 

```
     49         dist, nb_idx = self.env.KDTree.query(self.position(), k=2)
     50         nb_idx = nb_idx[1]
---> 51         self.target = self.env._sorted_agents[nb_idx]
IndexError: list index out of range
```

I think a similar error would be caused calling `space.neighbors()` when an agent in range was removed beforehand in the same timestep.

I looked into `space.py` and noticed the line
```
        self._cKDTree = None  # Reset KDTree
```
which is present in `move_agents()`, is not present in `remove_agents()`, nor in `add_agents()`. 

I understand redrawing the whole KDTree is costly so it wouldn't be practical to do so upon each of these function calls. I even checked `scipy.spacial.cKDTree` and I believe I have found it does not implement inserting nor removing nodes, which is what we would ideally use, am I right? 

I wish I could propose a workaround, but have not been able to think of an alternative. Just wanted to document this issue and confirm if I am understanding the implementation at present.

**Comment by JoelForamitti** [comment]
Thanks for reporting on this!

Indeed, one cannot add or remove nodes from a KDTree as far as I understand. For models where a lot of adding, deleting, and neighbor searching is done, one could think of a different neighbor search method.

But just to fix the bug for now, I think `add_agents` & `remove_agents` should set `_cKDTree` to `None` so that the tree is recalculated the next time that `cKDTree` is accessed.

Let me know if you'd be interested to make a PR for this!

**Comment by JoelForamitti** [comment]
This issue has now been fixed with https://github.com/JoelForamitti/agentpy/commit/db297668f187f7893ef3d653df640af24ed95783
