### ISSUE TITLE
[JOSS Review] Scenario comparison example

### ISSUE THREAD

**Issue by martibosch** [JoelForamitti/agentpy#15]
The docstring of the `scenarios` argument in `Experiment` does not give enough information, I have to go to the code to understand how it works. Additionally, I would highly recommend including the "scenario comparison" functionality in one of the example notebooks.

**Comment by JoelForamitti** [comment]
Hi @martibosch, thank you for pointing this out.
Indeed, the scenarios argument has not made it into any of the demonstration models
as it has proven more straight-forward to represent scenarios through different parameter combinations.
It will be depreciated in the upcoming release of v0.1.0.
