### ISSUE TITLE
[JOSS review] Manuscript corrections

### ISSUE THREAD

**Issue by martibosch** [JoelForamitti/agentpy#16]
## Statement of need

AFAIK, this section *must* be explicit in the manuscript. I suppose that such a section would include the sentence of lines 13-14. I would further suggest to make it a "self-contained" sentence (that does not require reading any other part of the manuscript to fully understand it), hence I would add: 

    The aim of agentpy is to provide an intuitive syntax for the creation of **agent-based** models together with
    advanced tools for scientific applications.
    
## Figure and code snippets

* Figure 1: it may be better to use a code snippet rather than a figure to display code, e.g., users might want to copy-paste them
* lines 27-30: it is better that the text refers to some code snippet in the manuscript (e.g., Figure 1). For instance: from the current manuscript, one may ask: what is `agents`? I had to open a notebook, instantiate some example `agentpy.Model`, inspect the class via `dir` and it is only then that I found the `agents` attribute

## Clarify some concepts and definitions

* line 30: what is the "record" action? I needed to go to the docstring of the `record` method to fully understand what it means. It may be a good idea to add a brief sentence to clarify it *within the manuscript* so that the reader can get a clearer picture there.
* line 45: "direct integration of analysis tools within the same framework" as somebody familiar with scientific Python, I suppose that you mean NumPy, pandas, NetworkX and the like, but it may be better to make it more explicit.

## Other

* line 29: IMHO "attribute" seems more Pythonic than "variable"
* links: it might be better to put URLs explicitly (e.g., although unlikely in JOSS, people might print the paper). Line 18 is fine since we can easily find the documentation without clicking the link, but not so much for line 46, where I believe that the word "here" should be replaced by the actual URL.

**Comment by JoelForamitti** [comment]
Dear @martibosch 

Thank you very much for your helpful review. I have just released AgentPy 0.1.0, together with a revised manuscript. Below I address your comments.

> Statement of need
> AFAIK, this section must be explicit in the manuscript. I suppose that such a section would include the sentence of lines 13-14. I would further suggest to make it a "self-contained" sentence (that does not require reading any other part of the manuscript to fully understand it), hence I would add:
> The aim of agentpy is to provide an intuitive syntax for the creation of **agent-based** models together with advanced tools for scientific applications.

There is now an explicit Statement of Need section in the manuscript. Although a different sentence is used, the term 'agent-based model' has been written out.

> Figure and code snippets
> ·	Figure 1: it may be better to use a code snippet rather than a figure to display code, e.g., users might want to copy-paste them
> ·	lines 27-30: it is better that the text refers to some code snippet in the manuscript (e.g., Figure 1). For instance: from the current manuscript, one may ask: what is agents? I had to open a notebook, instantiate some example agentpy.Model, inspect the class via dir and it is only then that I found the agents attribute

Thank you for pointing this out. Figure 1 has been removed and replaced by a whole new section ‘Usage Example’ that includes multiple code snippets.

The newest update of agentpy has also improved the syntax, so that the `agent` attribute now has to be declared explicitly in the model definition, as can be seen in the snippets.

> Clarify some concepts and definitions
> ·	line 30: what is the "record" action? I needed to go to the docstring of the record method to fully understand what it means. It may be a good idea to add a brief sentence to clarify it within the manuscript so that the reader can get a clearer picture there.

Apart from now providing full code snippets, a short sentence explaining record has been added and if one clicks on record they will be linked to the documentation.

> ·	line 45: "direct integration of analysis tools within the same framework" as somebody familiar with scientific Python, I suppose that you mean NumPy, pandas, NetworkX and the like, but it may be better to make it more explicit.

All the supported packages are now explicitly mentioned in the paper. They include EMA Workbench, NetworkX, NumPy, pandas, SALib, SciPy, and seaborn.

> Other
> ·	line 29: IMHO "attribute" seems more Pythonic than "variable"

This line has been removed in the revised paper.

> ·	links: it might be better to put URLs explicitly (e.g., although unlikely in JOSS, people might print the paper). Line 18 is fine since we can easily find the documentation without clicking the link, but not so much for line 46, where I believe that the word "here" should be replaced by the actual URL.

Explicit links are now given in footnotes for the AgentPy documentation and discussion forum, the comparison page, and the Mesa documentation.

**Comment by martibosch** [comment]
Hello again @JoelForamitti!

I have revised your comments and I find that most of my remarks have been addressed. The only part that I did not understand is the `agent` attribute, i.e.:

> The newest update of agentpy has also improved the syntax, so that the `agent` attribute now has to be declared explicitly in the model definition, as can be seen in the snippets.

what is the `agent` attribute? I cannot find it in any of the snippets - did you mean the `agents` attribute? If so, it is not declared explicitly in the `WealthAgent` snippet.

Best,
Martí

**Comment by JoelForamitti** [comment]
Hi @martibosch 

that was a typo from my side, i indeed meant `agents`, sorry. 

I copy here the model definition from the paper. You can see that `agents` is being declared in the model's setup function:

```python
class WealthModel(ap.Model):

    def setup(self):
        self.agents = ap.AgentList(self, self.p.n, WealthAgent)

    def step(self):
        self.agents.wealth_transfer()

    def end(self):
        self.agents.record('wealth')
```

In the `WealthAgent` snippet, the same attribute is accessed through `model.agents`.

Best,
Joël

**Comment by martibosch** [comment]
> that was a typo from my side, i indeed meant `agents`, sorry.

this is what I imagined, thank you for clarifying. However, [the latest (if I am not mistaken) version of the manuscript](https://github.com/openjournals/joss-reviews/issues/3065#issuecomment-850435847)  shows a different snippet (between lines 48 and 49) which does not explicitly declare the `agents` attribute in the `setup` method. Am I missing something?

Best,
Martí

**Comment by JoelForamitti** [comment]
The `agents` are declared not in the agent (lines 48-49), but in the model (lines 53-54, which is the snippet that i copied here).

**Comment by martibosch** [comment]
Indeed, my mistake, thank you for pointing it out!

Closing this then.
