### ISSUE TITLE
Empty cell tracking with multiple agents per cell throws error

### ISSUE THREAD

**Issue by steipatr** [JoelForamitti/agentpy#28]
If a grid is initiated with empty cell tracking, and an agent moves to a cell where there already is another agent, the second agent will try to remove that cell from the empty cells list. This throws a KeyError because the cell is already not in the empty cells list because the first agent previously removed it from the list.

## Expected Behavior
The model recognizes that the cell is already not empty.

## Current Behavior
An agent tries to remove a cell from the empty cells list when it moves there. If there already is an agent in that cell, this throws a KeyError since the cell is not in the empty cells list anymore.

## Possible Solution
Check if any other agents are in the cell, and consider that in https://github.com/JoelForamitti/agentpy/blob/480da12abc19e5c511e0e2e09ee5be44d285e69d/agentpy/grid.py#L286

## Steps to Reproduce
See attached notebook and data file. If you set the simulation steps to 10, you can see the agents move towards each other (and the cell marked with a green dot).

## Context (Environment)
I am implementing the Sugarscape in AgentPy. Windows 10 Enterprise, Python stuff:

agentpy                   0.1.2                    pypi_0    pypi
ipysimulate               0.2.0                    pypi_0    pypi
jupyterlab                3.0.16             pyhd8ed1ab_0    conda-forge
numpy                     1.20.3           py39ha4e8547_0
python                    3.9.6           h7840368_1_cpython    conda-forge

EDIT: seems similar to #21 and might be related (and therefore fixed?).

**Comment by JoelForamitti** [comment]
Hi @steipatr, thanks for reporting! It is a seperate issue from #21, so it isn't fixed yet. As you suggest, the track_empty condition has to be extended to account for multiple agents per cell.

**Comment by JoelForamitti** [comment]
Fixed with 9bc1c78dc0425e7afdeb1a70d46a6a8e468a921c
