### ISSUE TITLE
Flocking notebook - Question

### ISSUE THREAD

**Issue by gengala** [JoelForamitti/agentpy#51]
Hey,

awesome library!

A question. In your [flocking notebook](https://agentpy.readthedocs.io/en/latest/agentpy_flocking.html), where the parameters 'wall_avoidance_distance' and 'wall_avoidance_strength' (of the 3D case) are used? I don't think they are actually used.

**Comment by JoelForamitti** [comment]
Hi @gengala, thank you for spotting this, they are indeed not used.
